from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# --- File Metadata Schemas ---
class CreatedFileInfo(BaseModel):
    filename: str = Field(..., description="Name of the generated file (e.g. report.docx, chart.png)")
    directory: str = Field(default="", description="Directory where the file is stored on local disk")
    file_directory: Optional[str] = Field(default="", description="Directory where the file is stored on local disk")
    file_path: str = Field(..., description="Full absolute path to the file on local disk")
    output_directory: Optional[str] = Field(default="", description="Alias for directory for Java backend convenience")
    output_file_directory: Optional[str] = Field(default="", description="Alias for directory for Java backend convenience")
    download_url: str = Field(..., description="API endpoint to download or view the file")
    size_bytes: Optional[int] = Field(default=None, description="Size of the file in bytes")


# --- Agent State Schema ---
class AgentStateInfo(BaseModel):
    model_role: Optional[str] = Field(default=None, description="Role assigned by model router (e.g. general_model, coding_model)")
    model_name: Optional[str] = Field(default=None, description="Specific local Ollama model name used")
    analysis: Optional[Dict[str, Any]] = Field(default=None, description="Query analysis classification details")
    verified: Optional[bool] = Field(default=None, description="Whether the response passed verification")
    verification_reason: Optional[str] = Field(default=None, description="Verifier explanation or feedback")
    verification_attempts: Optional[int] = Field(default=None, description="Number of verification attempts made")
    tools_used: List[str] = Field(default=[], description="Tools invoked during agent execution")
    created_files: List[str] = Field(default=[], description="Full absolute file paths generated by tools in this turn")
    created_file_directories: List[str] = Field(default=[], description="Directories of generated files")
    directory: Optional[str] = Field(default=None, description="Directory where the generated file is stored")
    file_directory: Optional[str] = Field(default=None, description="Directory where the generated file is stored")
    output_directory: Optional[str] = Field(default=None, description="Directory path where generated files are stored")
    output_file_directory: Optional[str] = Field(default=None, description="Alias for output directory")


# --- Chat Schemas ---
class ChatRequest(BaseModel):
    query: str = Field(..., description="The user query or task instructions.")
    file_path: Optional[str] = Field(default="", description="Optional path to a local document or image.")
    thread_id: Optional[str] = Field(default="demo-user-1", description="Session/conversation ID for memory.")


class ChatResponse(BaseModel):
    query: str
    response: str
    model_role: Optional[str] = None
    model_name: Optional[str] = None
    verified: Optional[bool] = None
    verification_reason: Optional[str] = None
    verification_attempts: Optional[int] = None
    tools_used: List[str] = Field(default=[], description="Names of tools executed by the agent")
    required_tools: Optional[bool] = Field(default=None, description="Whether query analyzer determined tools were needed")
    analysis: Optional[Dict[str, Any]] = Field(default=None, description="Query analysis output")
    created_files: List[CreatedFileInfo] = Field(default=[], description="Files generated by AI tools with directory and metadata")
    output_directory: Optional[str] = Field(default=None, description="Primary output directory path where generated files are stored")
    file_directory: Optional[str] = Field(default=None, description="Directory path where generated files are stored")
    output_file_directory: Optional[str] = Field(default=None, description="Alias for file_directory")
    created_file_directory: Optional[str] = Field(default=None, description="Alias for file_directory")
    created_file_paths: List[str] = Field(default=[], description="Full absolute file paths of all generated files")
    created_file_directories: List[str] = Field(default=[], description="Directories where generated files reside")
    thread_id: str
    agent_state: Optional[AgentStateInfo] = Field(default=None, description="Complete AgentState snapshot")